makefile: fix snippet

diff --git a/shell/makefile.cheat b/shell/makefile.cheat
--- a/shell/makefile.cheat
+++ b/shell/makefile.cheat
@@ -11,10 +11,10 @@ YELLOW=\033[1;30;43m
 RED=\033[1;30;41m
 NC=\033[0m
 
-## hello: say hello
+ ## hello: say hello
 hello:
 	@if [ -z ${AUDIENCE} ]; then \
-		echo 'Missing `AUDIENCE` argument, usage: `make hello AUDIENCE=<audience>`' >/dev/stderr && exit 1; \
+		echo 'Missing "AUDIENCE" argument, usage: "make hello AUDIENCE=audience"' >/dev/stderr && exit 1; \
 	fi
 	@echo -e "${BLUE} I ${NC} Hello, ${AUDIENCE}."
 
